# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
=begin
Pais.create(iso2:'BO', nombre:'Bolivia')
Pais.create(iso2:'AR', nombre:'Argentina')
Pais.create(iso2:'BR', nombre:'Brasil')
Pais.create(iso2:'CL', nombre:'Chile')
Pais.create(iso2:'CN', nombre:'China')
Pais.create(iso2:'CO', nombre:'Colombia')
Pais.create(iso2:'EC', nombre:'Ecuador')
Pais.create(iso2:'KO', nombre:'Corea')
Pais.create(iso2:'MX', nombre:'Mexico')
Pais.create(iso2:'PE', nombre:'Peru')
Pais.create(iso2:'US', nombre:'EE.UU.')
=end
=begin
Persona.create(nombre:'Favio Jorge Yañiquez Monasterios')
Persona.create(nombre:'Empresa Nacional de Telecomunicaciones S.A.')
Persona.create(nombre:'Telefonica Celular de Bolivia S.A.')
Persona.create(nombre:'Nuevatel PCS de Bolivia S.A.')
Persona.create(nombre:'Coca Cola Co.')
Persona.create(nombre:'Soalpro S.R.L')
Persona.create(nombre:'Embotelladora Boliviana')
Persona.create(nombre:'CARSA Industria y Comercio S.R.L')
=end
=begin
Usuario.create(persona_id:1, identificacion:'fyaniquez', estado:'activo')
=end
=begin
Empresa.create(persona_id:1, pais_id:1, nit:'2710988016')
Empresa.create(persona_id:2, pais_id:1, nit:'1020703023')
Empresa.create(persona_id:3, pais_id:1, nit:'1020255020')
Empresa.create(persona_id:4, pais_id:1, nit:'1007179022')
=end
=begin
Marca.create(nombre:'Internet Coco', empresa_id: 1, activa:'si')
Marca.create(nombre:'ENTEL', empresa_id: 2, activa:'si')
Marca.create(nombre:'TIGO', empresa_id: 3, activa:'si')
Marca.create(nombre:'VIVA', empresa_id: 4, activa:'si')
=end
=begin
Capitulo.create(nombre:'Abarrotes')
Capitulo.create(nombre:'Enlatados')
Capitulo.create(nombre:'Lácteos')
Capitulo.create(nombre:'Golosinas')
Capitulo.create(nombre:'Horneados')
Capitulo.create(nombre:'Bebidas')
Capitulo.create(nombre:'Alcohólicos')
Capitulo.create(nombre:'Salud')
Capitulo.create(nombre:'Higiene')
Capitulo.create(nombre:'Limpieza')
Capitulo.create(nombre:'Comunicaciones')
Capitulo.create(nombre:'Bazar')
Capitulo.create(nombre:'Naturales')
Capitulo.create(nombre:'Servicios')
Capitulo.create(nombre:'Libreria')
Capitulo.create(nombre:'Electrónicos')
Capitulo.create(nombre:'Otros')
=end
=begin
Categoria.create(capitulo_id:1, nombre:'Aceite comestibles')
Categoria.create(capitulo_id:1, nombre:'Aderezos')
Categoria.create(capitulo_id:1, nombre:'Sopas en polvo')
Categoria.create(capitulo_id:1, nombre:'Crema de cacahuate')
Categoria.create(capitulo_id:1, nombre:'Crema para café')
Categoria.create(capitulo_id:1, nombre:'Pure de tomate')
Categoria.create(capitulo_id:1, nombre:'Alimento para mascotas')
Categoria.create(capitulo_id:1, nombre:'Granos')
Categoria.create(capitulo_id:1, nombre:'Azúcar')
Categoria.create(capitulo_id:1, nombre:'Café')
Categoria.create(capitulo_id:1, nombre:'Especias')
Categoria.create(capitulo_id:1, nombre:'Flan en polvo')
Categoria.create(capitulo_id:1, nombre:'Gelatinas')
Categoria.create(capitulo_id:1, nombre:'Harinas')
Categoria.create(capitulo_id:1, nombre:'Sal')
Categoria.create(capitulo_id:1, nombre:'Salsas')
Categoria.create(capitulo_id:1, nombre:'Sazonadores')
Categoria.create(capitulo_id:1, nombre:'Sopas')
Categoria.create(capitulo_id:1, nombre:'Mermeladas')
Categoria.create(capitulo_id:1, nombre:'Miel')
Categoria.create(capitulo_id:1, nombre:'Te')
Categoria.create(capitulo_id:1, nombre:'Cafe')
Categoria.create(capitulo_id:1, nombre:'Cocoa')
Categoria.create(capitulo_id:1, nombre:'Vinagre')
Categoria.create(capitulo_id:1, nombre:'Huevo')
Categoria.create(capitulo_id:1, nombre:'Fideos')
Categoria.create(capitulo_id:1, nombre:'Esencias')
Categoria.create(capitulo_id:1, nombre:'Jarabes')
Categoria.create(capitulo_id:1, nombre:'Cigarros')
Categoria.create(capitulo_id:1, nombre:'Manteca')
Categoria.create(capitulo_id:1, nombre:'Sopas precocidas')
Categoria.create(capitulo_id:2, nombre:'Frutas en almíbar')
Categoria.create(capitulo_id:2, nombre:'Sardinas')
Categoria.create(capitulo_id:2, nombre:'Atún')
Categoria.create(capitulo_id:2, nombre:'Maiz')
Categoria.create(capitulo_id:2, nombre:'Escabeche')
Categoria.create(capitulo_id:3, nombre:'Leche')
Categoria.create(capitulo_id:3, nombre:'Leche de soya')
Categoria.create(capitulo_id:3, nombre:'Crema')
Categoria.create(capitulo_id:3, nombre:'Yoghurt')
Categoria.create(capitulo_id:3, nombre:'Mantequilla')
Categoria.create(capitulo_id:3, nombre:'Margarina')
Categoria.create(capitulo_id:3, nombre:'Queso.')
Categoria.create(capitulo_id:4, nombre:'Snacks Dulces')
Categoria.create(capitulo_id:4, nombre:'Snacks Salados')
Categoria.create(capitulo_id:4, nombre:'Caramelos')
Categoria.create(capitulo_id:4, nombre:'Chupetes')
Categoria.create(capitulo_id:4, nombre:'Chocolates')
Categoria.create(capitulo_id:4, nombre:'Chicle')
Categoria.create(capitulo_id:4, nombre:'Gomitas')
Categoria.create(capitulo_id:4, nombre:'Masmelos')
Categoria.create(capitulo_id:4, nombre:'Pastillas')
Categoria.create(capitulo_id:4, nombre:'Alfajores')
Categoria.create(capitulo_id:4, nombre:'Galletas dulces')
Categoria.create(capitulo_id:4, nombre:'Galletas saladas')
Categoria.create(capitulo_id:4, nombre:'Grageas')
Categoria.create(capitulo_id:4, nombre:'Barras')
Categoria.create(capitulo_id:4, nombre:'Bombones')
Categoria.create(capitulo_id:4, nombre:'Helados')
Categoria.create(capitulo_id:4, nombre:'Gelatinas')
Categoria.create(capitulo_id:5, nombre:'Roscas')
Categoria.create(capitulo_id:5, nombre:'Galletas dulces')
Categoria.create(capitulo_id:5, nombre:'Galletas saladas')
Categoria.create(capitulo_id:5, nombre:'Galletas agua')
Categoria.create(capitulo_id:5, nombre:'Pastelitos')
Categoria.create(capitulo_id:5, nombre:'Pan en bolsa')
Categoria.create(capitulo_id:5, nombre:'Empanadas')
Categoria.create(capitulo_id:5, nombre:'Pan molido')
Categoria.create(capitulo_id:5, nombre:'Pan tostado.')
Categoria.create(capitulo_id:5, nombre:'Pan molde')
Categoria.create(capitulo_id:6, nombre:'Agua mineral')
Categoria.create(capitulo_id:6, nombre:'Agua natural')
Categoria.create(capitulo_id:6, nombre:'Agua saborizada')
Categoria.create(capitulo_id:6, nombre:'Jugos/Néctares')
Categoria.create(capitulo_id:6, nombre:'Bebidas de soya')
Categoria.create(capitulo_id:6, nombre:'Bebidas en polvo')
Categoria.create(capitulo_id:6, nombre:'Energetizantes')
Categoria.create(capitulo_id:6, nombre:'Isotónicos')
Categoria.create(capitulo_id:6, nombre:'Gaseosas')
Categoria.create(capitulo_id:6, nombre:'Infantiles')
Categoria.create(capitulo_id:6, nombre:'bicervecina')
Categoria.create(capitulo_id:6, nombre:'Base')
Categoria.create(capitulo_id:7, nombre:'Preparados')
Categoria.create(capitulo_id:7, nombre:'Cerveza')
Categoria.create(capitulo_id:7, nombre:'Singani')
Categoria.create(capitulo_id:7, nombre:'Brandy')
Categoria.create(capitulo_id:7, nombre:'Ron')
Categoria.create(capitulo_id:7, nombre:'Sidra')
Categoria.create(capitulo_id:7, nombre:'Whiskey')
Categoria.create(capitulo_id:7, nombre:'Vodka.')
Categoria.create(capitulo_id:7, nombre:'Vino')
Categoria.create(capitulo_id:8, nombre:'Agua oxigenada')
Categoria.create(capitulo_id:8, nombre:'Preservativos')
Categoria.create(capitulo_id:8, nombre:'Alcohol')
Categoria.create(capitulo_id:8, nombre:'Gasas')
Categoria.create(capitulo_id:8, nombre:'Analgésicos')
Categoria.create(capitulo_id:8, nombre:'Antigripales')
Categoria.create(capitulo_id:8, nombre:'Antiácidos.')
Categoria.create(capitulo_id:8, nombre:'Aspirinas')
Categoria.create(capitulo_id:8, nombre:'Curitas')
Categoria.create(capitulo_id:8, nombre:'Algodón')
Categoria.create(capitulo_id:9, nombre:'Toallas húmedas')
Categoria.create(capitulo_id:9, nombre:'Aceite para bebe')
Categoria.create(capitulo_id:9, nombre:'Toallas femeninas')
Categoria.create(capitulo_id:9, nombre:'Tinte para el cabello')
Categoria.create(capitulo_id:9, nombre:'Biberones')
Categoria.create(capitulo_id:9, nombre:'Talco')
Categoria.create(capitulo_id:9, nombre:'Cepillo de dientes')
Categoria.create(capitulo_id:9, nombre:'Shampoo')
Categoria.create(capitulo_id:9, nombre:'Acondicionador')
Categoria.create(capitulo_id:9, nombre:'Cotonetes')
Categoria.create(capitulo_id:9, nombre:'Afeitadoras')
Categoria.create(capitulo_id:9, nombre:'Cremas')
Categoria.create(capitulo_id:9, nombre:'Papel higiénico')
Categoria.create(capitulo_id:9, nombre:'Crema para afeitar')
Categoria.create(capitulo_id:9, nombre:'Dentífricos')
Categoria.create(capitulo_id:9, nombre:'Pañuelos desechables')
Categoria.create(capitulo_id:9, nombre:'Desodorantes')
Categoria.create(capitulo_id:9, nombre:'Maquillaje')
Categoria.create(capitulo_id:9, nombre:'Enjuague bucal')
Categoria.create(capitulo_id:9, nombre:'Lubricantes para labios')
Categoria.create(capitulo_id:9, nombre:'Gel')
Categoria.create(capitulo_id:9, nombre:'Loción')
Categoria.create(capitulo_id:9, nombre:'Jabon de tocador')
Categoria.create(capitulo_id:10, nombre:'Suavizante de telas')
Categoria.create(capitulo_id:10, nombre:'Sosa caustica')
Categoria.create(capitulo_id:10, nombre:'Detergente en polvo')
Categoria.create(capitulo_id:10, nombre:'Servilletas')
Categoria.create(capitulo_id:10, nombre:'Limpiador vajilla')
Categoria.create(capitulo_id:10, nombre:'Aromatizantes')
Categoria.create(capitulo_id:10, nombre:'Cera para automóvil')
Categoria.create(capitulo_id:10, nombre:'Cera para calzados')
Categoria.create(capitulo_id:10, nombre:'Pastillas sanitarias')
Categoria.create(capitulo_id:10, nombre:'Limpiadores pisos')
Categoria.create(capitulo_id:10, nombre:'Jabón de barra')
Categoria.create(capitulo_id:10, nombre:'Cloro')
Categoria.create(capitulo_id:10, nombre:'Insecticidas')
Categoria.create(capitulo_id:10, nombre:'Secadores')
Categoria.create(capitulo_id:10, nombre:'Desinfectantes')
Categoria.create(capitulo_id:10, nombre:'Guantes de goma')
Categoria.create(capitulo_id:10, nombre:'Escobas')
Categoria.create(capitulo_id:10, nombre:'Trapeador')
Categoria.create(capitulo_id:10, nombre:'Gomas baño')
Categoria.create(capitulo_id:10, nombre:'Sopapa')
Categoria.create(capitulo_id:10, nombre:'Trampas para ratas')
Categoria.create(capitulo_id:10, nombre:'Recogedor de metal/plástico')
Categoria.create(capitulo_id:10, nombre:'Jergas/Franelas')
Categoria.create(capitulo_id:10, nombre:'Matamoscas')
Categoria.create(capitulo_id:11, nombre:'Físicas')
Categoria.create(capitulo_id:11, nombre:'Lógicas')
Categoria.create(capitulo_id:12, nombre:'Pilas')
Categoria.create(capitulo_id:12, nombre:'fosforos')
Categoria.create(capitulo_id:12, nombre:'Velas')
Categoria.create(capitulo_id:12, nombre:'Cepillos')
Categoria.create(capitulo_id:12, nombre:'Cepillo de plástico')
Categoria.create(capitulo_id:12, nombre:'Vasos desechables')
Categoria.create(capitulo_id:12, nombre:'Cinta adhesiva')
Categoria.create(capitulo_id:12, nombre:'Cubiertos de plástico')
Categoria.create(capitulo_id:12, nombre:'Popotes')
Categoria.create(capitulo_id:12, nombre:'Platos desechables')
Categoria.create(capitulo_id:12, nombre:'Focos')
Categoria.create(capitulo_id:12, nombre:'Fusibles')
Categoria.create(capitulo_id:12, nombre:'Pegamento')
Categoria.create(capitulo_id:12, nombre:'Mecate/cuerda.')
Categoria.create(capitulo_id:13, nombre:'Frutas')
Categoria.create(capitulo_id:13, nombre:'Verduras')
Categoria.create(capitulo_id:13, nombre:'Pescados y mariscos.')
Categoria.create(capitulo_id:13, nombre:'Carnes')
Categoria.create(capitulo_id:13, nombre:'Embutidos')
Categoria.create(capitulo_id:13, nombre:'Panadería.')
Categoria.create(capitulo_id:13, nombre:'Quesos.')
Categoria.create(capitulo_id:13, nombre:'Tocino')
Categoria.create(capitulo_id:13, nombre:'Jamón')
Categoria.create(capitulo_id:13, nombre:'Congelados')
Categoria.create(capitulo_id:14, nombre:'Digitales')
Categoria.create(capitulo_id:14, nombre:'Documentos')
Categoria.create(capitulo_id:15, nombre:'Papel')
Categoria.create(capitulo_id:15, nombre:'Boligrafos')
Categoria.create(capitulo_id:15, nombre:'Pegamento')
Categoria.create(capitulo_id:15, nombre:'Cds')
Categoria.create(capitulo_id:15, nombre:'DVDs')
Categoria.create(capitulo_id:15, nombre:'Marcadores')
Categoria.create(capitulo_id:15, nombre:'Lapicez')
Categoria.create(capitulo_id:15, nombre:'Cuadernos')
Categoria.create(capitulo_id:15, nombre:'Folders')
Categoria.create(capitulo_id:15, nombre:'Flips')
Categoria.create(capitulo_id:15, nombre:'Bolsas')
Categoria.create(capitulo_id:15, nombre:'Fastener')
Categoria.create(capitulo_id:15, nombre:'Silicona')
Categoria.create(capitulo_id:16, nombre:'Audifonos')
Categoria.create(capitulo_id:16, nombre:'Memorias')
Categoria.create(capitulo_id:16, nombre:'Cargadores')
Categoria.create(capitulo_id:16, nombre:'Flashdisk')
=end
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Transcripciones', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Diseño', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Descargas', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:176, nombre:'Fotocopias', unidad:'hoja')
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Resúmenes', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Redacciones', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Cartas', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Contratos', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:175, nombre:'Horarios', unidad:'Bs')
Producto.create(usuario_id:1, marca_id:1, categoria_id:176, nombre:'Láminas', unidad:'hoja')
Producto.create(usuario_id:1, marca_id:2, categoria_id:149, nombre:'Hola 10', unidad:'tar')
Producto.create(usuario_id:1, marca_id:2, categoria_id:149, nombre:'Hola 15', unidad:'tar')
Producto.create(usuario_id:1, marca_id:2, categoria_id:149, nombre:'Hola 30', unidad:'tar')
Producto.create(usuario_id:1, marca_id:2, categoria_id:149, nombre:'Hola 50', unidad:'tar')
Producto.create(usuario_id:1, marca_id:2, categoria_id:149, nombre:'Hola 100', unidad:'tar')
Producto.create(usuario_id:1, marca_id:2, categoria_id:150, nombre:'Recarga', unidad:'Bs.')
Producto.create(usuario_id:1, marca_id:2, categoria_id:150, nombre:'Mayorista', unidad:'Bs.')
Producto.create(usuario_id:1, marca_id:2, categoria_id:149, nombre:'Chip', unidad:'u.')
Producto.create(usuario_id:1, marca_id:2, categoria_id:149, nombre:'Recup.Chip', unidad:'u.')

Producto.create(usuario_id:1, marca_id:3, categoria_id:149, nombre:'Tigo 10', unidad:'tar')
Producto.create(usuario_id:1, marca_id:3, categoria_id:149, nombre:'Tigo 20', unidad:'tar')
Producto.create(usuario_id:1, marca_id:3, categoria_id:149, nombre:'Tigo 30', unidad:'tar')
Producto.create(usuario_id:1, marca_id:3, categoria_id:149, nombre:'Tigo 50', unidad:'tar')
Producto.create(usuario_id:1, marca_id:3, categoria_id:149, nombre:'Tigo 100', unidad:'tar')
Producto.create(usuario_id:1, marca_id:3, categoria_id:150, nombre:'Recarga', unidad:'Bs.')
Producto.create(usuario_id:1, marca_id:3, categoria_id:149, nombre:'Chip', unidad:'u.')
Producto.create(usuario_id:1, marca_id:3, categoria_id:149, nombre:'Recup.Chip', unidad:'u.')

Producto.create(usuario_id:1, marca_id:4, categoria_id:149, nombre:'Viva 10', unidad:'tar')
Producto.create(usuario_id:1, marca_id:4, categoria_id:149, nombre:'Viva 20', unidad:'tar')
Producto.create(usuario_id:1, marca_id:4, categoria_id:149, nombre:'Viva 30', unidad:'tar')
Producto.create(usuario_id:1, marca_id:4, categoria_id:149, nombre:'Viva 50', unidad:'tar')
Producto.create(usuario_id:1, marca_id:4, categoria_id:149, nombre:'Viva 100', unidad:'tar')
Producto.create(usuario_id:1, marca_id:4, categoria_id:150, nombre:'Recarga', unidad:'Bs.')
Producto.create(usuario_id:1, marca_id:4, categoria_id:149, nombre:'Chip', unidad:'u.')
Producto.create(usuario_id:1, marca_id:4, categoria_id:150, nombre:'Mayorista', unidad:'Bs.')

#=end
